START, CHOOSING, ENTRY, TYPING_CHOICE, SET_LINK, CATEGORY, SET_CATEGORY, RM_CATEGORY = range(8)
KEYBOARD_GET_KEY = "get"
KEYBOARD_REMOVE_KEY = "remove"
KEYBOARD_AUTO_KEY = "auto"
KEYBOARD_MANUAL_KEY = "manual"
KEYBOARD_NEXT_KEY = "next"
KEYBOARD_STOP_KEY = "stop"
