(
    START,
    CHOOSING,
    ENTRY,
    LINK,
    TYPING_CHOICE,
    SET_LINK,
    CATEGORY,
    SET_CATEGORY,
    RM_CATEGORY,
    DOMAIN,
    RM_DOMAIN,
    UPDATE_CATEGORY,
    STATUS,
    GET_STATUS,
) = range(14)

KEYBOARD_GET_KEY = "get"
KEYBOARD_REMOVE_KEY = "remove"
KEYBOARD_UPDATE_KEY = "update"
KEYBOARD_SYNC_KEY = "sync"

KEYBOARD_AUTO_KEY = "auto"
KEYBOARD_MANUAL_KEY = "manual"

KEYBOARD_NEXT_KEY = "next"
KEYBOARD_STOP_KEY = "stop"

CATEGORY_PROPERTY = "Category"
DOMAIN_PROPERTY = "Domain"
CATEGORY_STATUS = "Status"

STATUS_TODO = "To Do"

LINK_TYPE = "link"
CINEMA_TYPE = "cinema"
