name: Docker Image CI

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}   
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ag0n1k/notion-bot:${GITHUB_REF##*/}
      - name: Push the Docker image
        run: |
          docker push ag0n1k/notion-bot:${GITHUB_REF##*/}
          docker push ag0n1k/notion-bot:latest
