name: Docker Image CI/CD

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}   
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ag0n1k/notion-bot:${GITHUB_REF##*/}
      - name: Push the Docker image
        run: |
          docker push ag0n1k/notion-bot:${GITHUB_REF##*/}
          docker push ag0n1k/notion-bot:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH action
        uses: appleboy/ssh-action@master
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.RSA_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Stop all running Docker Containers
            docker kill $(docker ps -q)

            # Free up space
            docker system prune -a

            # Pull the Docker Image
            docker pull ag0n1k/notion-bot:${GITHUB_REF##*/}

            # Run a new container from a new image
            docker run -dit ag0n1k/notion-bot:${GITHUB_REF##*/}
